# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://blog.farzaaaan.com/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]

# [[params.social]]
#   name = "Github"
#   icon = "fa fa-github fa-2x"
#   weight = 1
#   url = "https://github.com/johndoe/"
# [[params.social]]
#   name = "Gitlab"
#   icon = "fa fa-gitlab fa-2x"
#   weight = 2
#   url = "https://gitlab.com/johndoe/"
# [[params.social]]
#   name = "Twitter"
#   icon = "fa fa-twitter fa-2x"
#   weight = 3
#   url = "https://twitter.com/johndoe/"