baseURL = 'https://blog.farzaaaan.com/'
languageCode = 'en-us'
theme = 'LoveIt'


enableGitInfo = true

[menu]
[[menu.main]]
    weight = 5
    identifier = "twitter"
    pre = "<i class='fab fa-twitter fa-fw' aria-hidden='true'></i>"
    post = ""
    name = ""
    url = "https://twitter.com/farzaaaan"
    title = "Twitter"
[[menu.main]]
    weight = 6
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
    post = ""
    name = ""
    url = "https://github.com/farzaaaan"
    title = "GitHub"
[[menu.main]]
    weight = 7
    identifier = "linkedin"
    pre = "<i class='fab fa-linkedin fa-fw' aria-hidden='true'></i>"
    post = ""
    name = ""
    url = "https://www.linkedin.com/in/farzanmirheydari/"
    title = "LinkedIn"

[author]
    name = ' farzan'

[params]
  gitRepo = "https://github.com/farzaaaan/blog"

[params.header]
    [params.header.title]
        name = ""
        typeit = true
        pre = "<i class='far fa-terminal fa-solid' aria-hidden='true'></i>"

[params.home]
    [params.home.profile]
        subtitle = ''
        typeit = false

# [params.social]
#     github = 'farzaaaan'
#     linkedin = 'farzaaaan'
#     twitter = 'farzaaaan'
#     email = 'me@farzaaan.com'

[params.footer]
hugo = false
author = false
custom = 'Humata, Huxta, Huvarshta'
copyright = false

[params.search]
enable = true


[params.page.share]
      enable = true
      Twitter = true
      Facebook = false
      Linkedin = true
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Flipboard = false
      Weibo = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false